### ISSUE TITLE
website glitch

### ISSUE THREAD

**Issue by gamer191** [xbarin02/collatz#5]
The website (collatz-problem.org) seems to have a glitch that's making the assignment percentage show as more than 100%. Also, the time left for verification is stuck on `Calculating...`
![screenshot of problem](https://user-images.githubusercontent.com/83270075/182054360-bf7974f5-edc5-403d-a8e9-d7f39e960c3e.png)

**Comment by xbarin02** [comment]
Fixed. This happens when the client that collects lowest incomplete assignments freezes.

**Comment by gamer191** [comment]
![image](https://github.com/xbarin02/collatz/assets/83270075/571d00dd-0281-4784-95e0-c74f1f1c8082)
This is happening again. I should note that lowest unassigned is increasing rapidly, and lowest incomplete is increasing slowly, making me think one of the supercomputers is having issues or something like that

PS: `Lowest incomplete` obviously tells us the lowest number that the computer hasn't tested. If the computer found a number that doesn't fit the collatz conjecture, would `Lowest incomplete` freeze, or would it keep increasing, since technically the computer has tested that number

**Comment by xbarin02** [comment]
This happens because the job scheduler on some supercomputer kills thousands of my workers. I don't know exactly why this is happening. But it's sporadic. I have a lowest incomplete assignments collector running on one of my computers. It'll catch up with this glitch in a few days.

If the computer found a number that doesn't fit the Collatz conjecture, the system would freeze the Lowest incomplete  assignment (no worker can solve it).

Thanks for reporting the bug.

David Barina

**Comment by gamer191** [comment]
> If the computer found a number that doesn't fit the Collatz conjecture, the system would freeze the Lowest incomplete assignment (no worker can solve it).

How many computers would be trying to solve it? I worry that eventually one (or two, if that's required for verification) of them would solve it due to an arithmetic error.

**Comment by xbarin02** [comment]
Solving includes thousands of CPUs and GPUs working simultaneously.

If you are worried about hardware failure, in 2017 the yoyo@home project checked all numbers up to 87 * 2^60. Up to this limit, our results are consistent.
